import type { Metadata } from "next";
import { Providers } from "@/app/(frontend)/providers";
import { Inter, Merriweather } from "next/font/google";
import "@/app/(frontend)/globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});
const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-serif",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${inter.variable} ${merriweather.variable} antialiased text-body`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
